### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [T1rax/movies_async_api_service#46]
Отличная работа 👍 Все учтено и реализовано на высоком уровне. Можно немного доработать следующие моменты:
1. В скриптах ожидания ES и Redis в тестах (tests/functional/utils/wait_for_es.py и tests/functional/utils/wait_for_redis.py) вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток.
2. С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим conftest.py. Для этого в conftest.py есть [pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html#using-fixtures-from-other-projects)
3. Не используйте прямое указание кодов ответов сервера в тестах (200, 400 и т.д.), применяйте http.HTTPStatus. Этим можно немного повысить читаемость кода https://docs.python.org/3/library/http.html#http.HTTPStatus
4. В fast_api/api/v1 много раз встречается вот такая конструкция в параметрах методов:
      ```
      page_number: int = Query(default=1, gt=0, le=100),
      page_size: int = Query(default=50, gt=0, le=100),
      ```
      Можно попробовать вынести эту пару в отдельный класс, какой-нибудь PaginatedParams, инжектить его в качестве зависимости в параметры методов и работать с ними как с объектом. Т.о. параметры пагинации будут в одном месте и при необходимости легко будет их изменить сразу и везде.
5. Можно лучше: рекомендую почитать [этот](https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values) блок про сеттинги. По ссылке выше описан способ как учитывать префикс сабмоделей в имени env переменной
      ```
      class AppSettings(BaseSettings):
          host: str = Field('localhost')
      
      class Config(BaseSettings):
          app: AppSettings = AppSettings()
          
          class Config:
              env_prefix = 'AUTH_'
              env_nested_delimiter = '_'
      ```
      и просто делаете env переменнную вида: AUTH_APP_HOST.

      p.s. По умолчанию у pydantic-сеттингов маппинг регистронезависимый. То есть не нужно писать атрибуты класса в верхнем регистре, что кстати немного нарушает PEP8 (у вас в fast_api/core/config.py много капслока)
6. Вот [тут](https://github.com/T1rax/movies_async_api_service/blob/4fcbde5e4205e48e030cb0f380b4dd5c0a05dc8a/fast_api/services/film.py#L80) у вас "захардкожены" redis и ES. А что делать если завтра будет принято решение для кэширования использовать memcached или ES заменить на что-то [другое](https://habr.com/ru/post/581394/).
Эта задача решается использованием абстрактных классов.  
Например таким:
      ```
      class AsyncCacheStorage(ABC):
          @abstractmethod
          async def get(self, key: str, **kwargs):
              pass
      
          @abstractmethod
          async def set(self, key: str, value: str, expire: int, **kwargs):
              pass
      
      ```
      И тогда `redis: Redis = Depends(get_redis)` можно заменить на `cache: AsyncCacheStorage = Depends(get_redis),` главное чтобы используемый модуль кэширования реализовывал методы класса AsyncCacheStorage. И если завтра решат перейти на memcached то нам останется лишь изменить  `cache: AsyncCacheStorage = Depends(get_memcached),`.
      Тоже самое и с полнотекстовым поиском можно провернуть.

**Comment by T1rax** [comment]
Разделили на 2 задачи, эту закрываем:
[Код ревью - инфрастуктура тестов и кеширование#47](https://github.com/T1rax/movies_async_api_service/issues/47)
[Код ревью - конфиги и настройки API#48](https://github.com/T1rax/movies_async_api_service/issues/48)
